package com.fanap.bankservicesystem.business.exception;

public interface ExceptionMessageCodes {

    String BSS_NEGATIVE_AMOUNT = "BSS_NEGATIVE_AMOUNT_IS_NOT_VALID";
    String BSS_NEGATIVE_INPUT_VALUE = "BSS_NEGATIVE_INPUT_VALUE_IS_NOT_VALID";
    String BSS_EMPTY_STRING = "BSS_EMPTY_STRING_IS_NOT_VALID";

    String BSS_INSUFFICIENT_BALANCE = "BSS_BALANCE_IS_INSUFFICIENT";
    String BSS_INSUFFICIENT_BALANCE_AND_OVER_DRAFT_LIMIT = "BSS_SUM_OF_BALANCE_AND_OVER_DRAFT_LIMIT_IS_INSUFFICIENT";
    String BSS_MINIMUM_BALANCE_LIMIT = "BSS_MINIMUM_BALANCE_LIMIT_VIOLATED";

}
